apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: policies.authentication.knative.dev
spec:
  group: authentication.knative.dev
  names:
    kind: Policy
    plural: policies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            originIsOptional:
              type: boolean
            origins:
              items:
                properties:
                  jwt:
                    properties:
                      audiences:
                        items:
                          type: string
                        type: array
                      excludedPaths:
                        items:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                        type: array
                      issuer:
                        type: string
                      jwksUri:
                        type: string
                      jwtHeaders:
                        items:
                          type: string
                        type: array
                      jwtParams:
                        items:
                          type: string
                        type: array
                    type: object
                type: object
              type: array
            peerIsOptional:
              type: boolean
            peers:
              items:
                properties:
                  jwt:
                    properties:
                      audiences:
                        items:
                          type: string
                        type: array
                      excludedPaths:
                        items:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                        type: array
                      issuer:
                        type: string
                      jwksUri:
                        type: string
                      jwtHeaders:
                        items:
                          type: string
                        type: array
                      jwtParams:
                        items:
                          type: string
                        type: array
                    type: object
                  mtls:
                    properties:
                      allowTls:
                        type: boolean
                      mode:
                        type: string
                    type: object
                type: object
              type: array
            principalBinding:
              type: string
            targets:
              items:
                properties:
                  name:
                    type: string
                  ports:
                    items:
                      properties:
                        name:
                          type: string
                        number:
                          format: int32
                          type: integer
                      type: object
                    type: array
                required:
                - name
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
