apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: addressabletypes.duck.knative.dev
spec:
  group: duck.knative.dev
  names:
    kind: AddressableType
    plural: addressabletypes
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        status:
          properties:
            address:
              properties:
                hostname:
                  type: string
              type: object
          type: object
      required:
      - status
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
