apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: virtualservices.networking.knative.dev
spec:
  group: networking.knative.dev
  names:
    kind: VirtualService
    plural: virtualservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            gateways:
              items:
                type: string
              type: array
            hosts:
              items:
                type: string
              type: array
            http:
              items:
                properties:
                  appendHeaders:
                    type: object
                  corsPolicy:
                    properties:
                      allowCredentials:
                        type: boolean
                      allowHeaders:
                        items:
                          type: string
                        type: array
                      allowMethods:
                        items:
                          type: string
                        type: array
                      allowOrigin:
                        items:
                          type: string
                        type: array
                      exposeHeaders:
                        items:
                          type: string
                        type: array
                      maxAge:
                        type: string
                    type: object
                  fault:
                    properties:
                      abort:
                        properties:
                          httpStatus:
                            format: int64
                            type: integer
                          percent:
                            format: int64
                            type: integer
                        required:
                        - httpStatus
                        type: object
                      delay:
                        properties:
                          exponentialDelay:
                            type: string
                          fixedDelay:
                            type: string
                          percent:
                            format: int64
                            type: integer
                        required:
                        - fixedDelay
                        type: object
                    type: object
                  match:
                    items:
                      properties:
                        authority:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                        gateways:
                          items:
                            type: string
                          type: array
                        headers:
                          type: object
                        method:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                        port:
                          format: int32
                          type: integer
                        scheme:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                        sourceLabels:
                          type: object
                        uri:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                            suffix:
                              type: string
                          type: object
                      type: object
                    type: array
                  mirror:
                    properties:
                      host:
                        type: string
                      port:
                        properties:
                          name:
                            type: string
                          number:
                            format: int32
                            type: integer
                        type: object
                      subset:
                        type: string
                    required:
                    - host
                    type: object
                  redirect:
                    properties:
                      authority:
                        type: string
                      uri:
                        type: string
                    type: object
                  removeResponseHeaders:
                    type: object
                  retries:
                    properties:
                      attempts:
                        format: int64
                        type: integer
                      perTryTimeout:
                        type: string
                    required:
                    - attempts
                    - perTryTimeout
                    type: object
                  rewrite:
                    properties:
                      authority:
                        type: string
                      uri:
                        type: string
                    type: object
                  route:
                    items:
                      properties:
                        destination:
                          properties:
                            host:
                              type: string
                            port:
                              properties:
                                name:
                                  type: string
                                number:
                                  format: int32
                                  type: integer
                              type: object
                            subset:
                              type: string
                          required:
                          - host
                          type: object
                        weight:
                          format: int64
                          type: integer
                      required:
                      - destination
                      - weight
                      type: object
                    type: array
                  timeout:
                    type: string
                  websocketUpgrade:
                    type: boolean
                type: object
              type: array
            tcp:
              items:
                properties:
                  match:
                    items:
                      properties:
                        destinationSubnets:
                          items:
                            type: string
                          type: array
                        gateways:
                          items:
                            type: string
                          type: array
                        port:
                          format: int64
                          type: integer
                        sourceLabels:
                          type: object
                      type: object
                    type: array
                  route:
                    items:
                      properties:
                        destination:
                          properties:
                            host:
                              type: string
                            port:
                              properties:
                                name:
                                  type: string
                                number:
                                  format: int32
                                  type: integer
                              type: object
                            subset:
                              type: string
                          required:
                          - host
                          type: object
                        weight:
                          format: int64
                          type: integer
                      required:
                      - destination
                      - weight
                      type: object
                    type: array
                required:
                - match
                - route
                type: object
              type: array
            tls:
              items:
                properties:
                  match:
                    items:
                      properties:
                        destinationSubnets:
                          items:
                            type: string
                          type: array
                        gateways:
                          items:
                            type: string
                          type: array
                        port:
                          format: int64
                          type: integer
                        sniHosts:
                          items:
                            type: string
                          type: array
                        sourceLabels:
                          type: object
                      required:
                      - sniHosts
                      type: object
                    type: array
                  route:
                    items:
                      properties:
                        destination:
                          properties:
                            host:
                              type: string
                            port:
                              properties:
                                name:
                                  type: string
                                number:
                                  format: int32
                                  type: integer
                              type: object
                            subset:
                              type: string
                          required:
                          - host
                          type: object
                        weight:
                          format: int64
                          type: integer
                      required:
                      - destination
                      - weight
                      type: object
                    type: array
                required:
                - match
                - route
                type: object
              type: array
          required:
          - hosts
          type: object
      required:
      - spec
      type: object
  version: v1alpha3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
