apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gateways.networking.knative.dev
spec:
  group: networking.knative.dev
  names:
    kind: Gateway
    plural: gateways
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            selector:
              type: object
            servers:
              items:
                properties:
                  hosts:
                    items:
                      type: string
                    type: array
                  port:
                    properties:
                      name:
                        type: string
                      number:
                        format: int64
                        type: integer
                      protocol:
                        type: string
                    required:
                    - number
                    - protocol
                    type: object
                  tls:
                    properties:
                      caCertificates:
                        type: string
                      httpsRedirect:
                        type: boolean
                      mode:
                        type: string
                      privateKey:
                        type: string
                      serverCertificate:
                        type: string
                      subjectAltNames:
                        items:
                          type: string
                        type: array
                    required:
                    - httpsRedirect
                    - serverCertificate
                    - privateKey
                    - caCertificates
                    - subjectAltNames
                    type: object
                required:
                - port
                type: object
              type: array
          required:
          - servers
          type: object
      required:
      - spec
      type: object
  version: v1alpha3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
