apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: destinationrules.networking.knative.dev
spec:
  group: networking.knative.dev
  names:
    kind: DestinationRule
    plural: destinationrules
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            host:
              type: string
            subsets:
              items:
                properties:
                  labels:
                    type: object
                  name:
                    type: string
                  trafficPolicy:
                    properties:
                      connectionPool:
                        properties:
                          http:
                            properties:
                              maxRequestsPerConnection:
                                format: int32
                                type: integer
                              maxRetries:
                                format: int32
                                type: integer
                            type: object
                          tcp:
                            properties:
                              connectTimeout:
                                type: string
                              maxConnections:
                                format: int32
                                type: integer
                            type: object
                        type: object
                      loadBalancer:
                        properties:
                          consistentHash:
                            properties:
                              httpCookie:
                                properties:
                                  name:
                                    type: string
                                  path:
                                    type: string
                                  ttl:
                                    type: string
                                required:
                                - name
                                - ttl
                                type: object
                              httpHeaderName:
                                type: string
                              minimumRingSize:
                                format: int64
                                type: integer
                              useSourceIp:
                                type: boolean
                            type: object
                          simple:
                            type: string
                        type: object
                      outlierDetection:
                        properties:
                          baseEjectionTime:
                            type: string
                          consecutiveErrors:
                            format: int32
                            type: integer
                          interval:
                            type: string
                          maxEjectionPercent:
                            format: int32
                            type: integer
                        type: object
                      portLevelSettings:
                        items:
                          properties:
                            connectionPool:
                              properties:
                                http:
                                  properties:
                                    maxRequestsPerConnection:
                                      format: int32
                                      type: integer
                                    maxRetries:
                                      format: int32
                                      type: integer
                                  type: object
                                tcp:
                                  properties:
                                    connectTimeout:
                                      type: string
                                    maxConnections:
                                      format: int32
                                      type: integer
                                  type: object
                              type: object
                            loadBalancer:
                              properties:
                                consistentHash:
                                  properties:
                                    httpCookie:
                                      properties:
                                        name:
                                          type: string
                                        path:
                                          type: string
                                        ttl:
                                          type: string
                                      required:
                                      - name
                                      - ttl
                                      type: object
                                    httpHeaderName:
                                      type: string
                                    minimumRingSize:
                                      format: int64
                                      type: integer
                                    useSourceIp:
                                      type: boolean
                                  type: object
                                simple:
                                  type: string
                              type: object
                            outlierDetection:
                              properties:
                                baseEjectionTime:
                                  type: string
                                consecutiveErrors:
                                  format: int32
                                  type: integer
                                interval:
                                  type: string
                                maxEjectionPercent:
                                  format: int32
                                  type: integer
                              type: object
                            port:
                              properties:
                                name:
                                  type: string
                                number:
                                  format: int32
                                  type: integer
                              type: object
                            tls:
                              properties:
                                caCertificates:
                                  type: string
                                clientCertificate:
                                  type: string
                                mode:
                                  type: string
                                privateKey:
                                  type: string
                                sni:
                                  type: string
                                subjectAltNames:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - mode
                              type: object
                          required:
                          - port
                          type: object
                        type: array
                      tls:
                        properties:
                          caCertificates:
                            type: string
                          clientCertificate:
                            type: string
                          mode:
                            type: string
                          privateKey:
                            type: string
                          sni:
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                        required:
                        - mode
                        type: object
                    type: object
                required:
                - name
                - labels
                type: object
              type: array
            trafficPolicy:
              properties:
                connectionPool:
                  properties:
                    http:
                      properties:
                        maxRequestsPerConnection:
                          format: int32
                          type: integer
                        maxRetries:
                          format: int32
                          type: integer
                      type: object
                    tcp:
                      properties:
                        connectTimeout:
                          type: string
                        maxConnections:
                          format: int32
                          type: integer
                      type: object
                  type: object
                loadBalancer:
                  properties:
                    consistentHash:
                      properties:
                        httpCookie:
                          properties:
                            name:
                              type: string
                            path:
                              type: string
                            ttl:
                              type: string
                          required:
                          - name
                          - ttl
                          type: object
                        httpHeaderName:
                          type: string
                        minimumRingSize:
                          format: int64
                          type: integer
                        useSourceIp:
                          type: boolean
                      type: object
                    simple:
                      type: string
                  type: object
                outlierDetection:
                  properties:
                    baseEjectionTime:
                      type: string
                    consecutiveErrors:
                      format: int32
                      type: integer
                    interval:
                      type: string
                    maxEjectionPercent:
                      format: int32
                      type: integer
                  type: object
                portLevelSettings:
                  items:
                    properties:
                      connectionPool:
                        properties:
                          http:
                            properties:
                              maxRequestsPerConnection:
                                format: int32
                                type: integer
                              maxRetries:
                                format: int32
                                type: integer
                            type: object
                          tcp:
                            properties:
                              connectTimeout:
                                type: string
                              maxConnections:
                                format: int32
                                type: integer
                            type: object
                        type: object
                      loadBalancer:
                        properties:
                          consistentHash:
                            properties:
                              httpCookie:
                                properties:
                                  name:
                                    type: string
                                  path:
                                    type: string
                                  ttl:
                                    type: string
                                required:
                                - name
                                - ttl
                                type: object
                              httpHeaderName:
                                type: string
                              minimumRingSize:
                                format: int64
                                type: integer
                              useSourceIp:
                                type: boolean
                            type: object
                          simple:
                            type: string
                        type: object
                      outlierDetection:
                        properties:
                          baseEjectionTime:
                            type: string
                          consecutiveErrors:
                            format: int32
                            type: integer
                          interval:
                            type: string
                          maxEjectionPercent:
                            format: int32
                            type: integer
                        type: object
                      port:
                        properties:
                          name:
                            type: string
                          number:
                            format: int32
                            type: integer
                        type: object
                      tls:
                        properties:
                          caCertificates:
                            type: string
                          clientCertificate:
                            type: string
                          mode:
                            type: string
                          privateKey:
                            type: string
                          sni:
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                        required:
                        - mode
                        type: object
                    required:
                    - port
                    type: object
                  type: array
                tls:
                  properties:
                    caCertificates:
                      type: string
                    clientCertificate:
                      type: string
                    mode:
                      type: string
                    privateKey:
                      type: string
                    sni:
                      type: string
                    subjectAltNames:
                      items:
                        type: string
                      type: array
                  required:
                  - mode
                  type: object
              type: object
          required:
          - host
          type: object
      required:
      - spec
      type: object
  version: v1alpha3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
